kind: PersistentVolume
apiVersion: v1
metadata:
  name: podcast-pv
  labels:
    type: local
spec:
  storageClassName: podcast-pv-class
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/cychong/work/cbs-ost/public"
