{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.pvcName | quote }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes: 
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}
