apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
{{ include "nginx.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy : {{ .Values.service.externalTrafficPolicy }}
  externalIPs : {{ .Values.service.externalIPs }}
  {{- end}}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      targetPort: {{ .Values.service.targetPort }}
      {{- end}}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
