apiVersion: v1
kind: Service
metadata:
  name: {{ include "slackbot.fullname" . }}
  labels:
    {{- include "slackbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy : {{ .Values.service.externalTrafficPolicy }}
  {{- end}}
  externalIPs : {{ .Values.service.externalIPs }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      targetPort: {{ .Values.service.targetPort }}
      {{- end}}
      protocol: TCP
      name: http
  selector:
    {{- include "slackbot.selectorLabels" . | nindent 4 }}
