{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-pvc
  labels:
    type: local
spec:
        #  storageClassName: 
        #    - {{ .Values.persistence.storageClassName }}
  storageClassName: manual
  accessModes: 
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}
