apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-ghost-helm.fullname" . }}
  labels:
{{ include "my-ghost-helm.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy : {{ .Values.service.externalTrafficPolicy }}
  externalTPs : {{ .Values.service.externalIPs }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "my-ghost-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
